name: CI 

on: 
  workflow_dispatch: {}
  repository_dispatch:
    types: [ping]
  push:
    branches:
      - "dev"

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: setup the environment
      run: echo "Initial setup completed"